[workspace]
members = [
    "circuits/transfer",
    "circuits/lock",
    "circuits/withdraw",
    "circuits/process_pending_deposits",
    "circuits/process_pending_transfers",
    "circuits/add_eth_signer",
    "circuits/extensions/fundraiser/correct_addition",
    "circuits/extensions/fundraiser/correct_zero",
    "circuits/extensions/fundraiser/met_threshold",
    "circuits/extensions/fundraiser/revoke_contribution",
    "circuits/extensions/private_voting/check_owner",
    "circuits/extensions/private_voting/check_vote",
    "circuits/extensions/private_voting/process_votes",
    "circuits/extensions/auction/consolidate_bids",
    "circuits/extensions/auction/private_bid_greater",

]
default-member = "circuits/transfer"

